#!/bin/bash
# Pandoc Markdown to PDF Script by Felix Münscher
filename=$(basename -- "$1")
extension="${filename##*.}"
filename="${filename%.*}"
pandoc $1 -s -H css/markdown_pandoc.css -f markdown_github-hard_line_breaks -t html --pdf-engine=wkhtmltopdf -o $filename.pdf
